// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.src.Data;

#nullable disable

namespace TMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308093553_UpdateUsersTable")]
    partial class UpdateUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TMS.src.UserModel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<string>("age")
                        .HasColumnType("longtext");

                    b.Property<int?>("assigned_truck_id")
                        .HasColumnType("int");

                    b.Property<string>("cnic")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("device_token")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("emergency_contact")
                        .HasColumnType("longtext");

                    b.Property<int?>("experience_years")
                        .HasColumnType("int");

                    b.Property<string>("f_Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_available")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("is_verified")
                        .HasColumnType("longtext");

                    b.Property<string>("l_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("license_number")
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .HasColumnType("longtext");

                    b.Property<string>("phone_no")
                        .HasColumnType("longtext");

                    b.Property<string>("profile_image")
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .HasColumnType("longtext");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("verification_status")
                        .HasColumnType("longtext");

                    b.HasKey("userId");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
