// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.src.Data;

#nullable disable

namespace TMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308163617_AddtripRelationshipToTruck")]
    partial class AddtripRelationshipToTruck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TMS.src.ExpenseCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("expenseCategories");
                });

            modelBuilder.Entity("TMS.src.ExpenseModel", b =>
                {
                    b.Property<int>("expenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("expenseId"));

                    b.Property<int?>("added_by")
                        .HasColumnType("int");

                    b.Property<double?>("amount")
                        .HasColumnType("double");

                    b.Property<string>("client_Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("co_driver_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("date")
                        .HasColumnType("longtext");

                    b.Property<int?>("driver_id")
                        .HasColumnType("int");

                    b.Property<int?>("e_c_id")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .HasColumnType("longtext");

                    b.Property<string>("notes")
                        .HasColumnType("longtext");

                    b.Property<string>("receipt_url")
                        .HasColumnType("longtext");

                    b.Property<string>("time")
                        .HasColumnType("longtext");

                    b.Property<int?>("trip_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("expenseId");

                    b.HasIndex("added_by");

                    b.HasIndex("co_driver_id");

                    b.HasIndex("driver_id");

                    b.HasIndex("e_c_id");

                    b.HasIndex("trip_id");

                    b.ToTable("expenses");
                });

            modelBuilder.Entity("TMS.src.TripModel", b =>
                {
                    b.Property<int>("tripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("tripId"));

                    b.Property<DateTime?>("actual_end_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("actual_start_time")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("allowance")
                        .HasColumnType("double");

                    b.Property<string>("client_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("client_company")
                        .HasColumnType("longtext");

                    b.Property<string>("client_contact")
                        .HasColumnType("longtext");

                    b.Property<int?>("co_driver_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("destination")
                        .HasColumnType("longtext");

                    b.Property<double?>("distance_km")
                        .HasColumnType("double");

                    b.Property<int?>("driver_id")
                        .HasColumnType("int");

                    b.Property<int?>("estimated_time_min")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("notes")
                        .HasColumnType("longtext");

                    b.Property<int?>("odometer_end")
                        .HasColumnType("int");

                    b.Property<int?>("odometer_start")
                        .HasColumnType("int");

                    b.Property<string>("pickup_location")
                        .HasColumnType("longtext");

                    b.Property<string>("scheduled_date")
                        .HasColumnType("longtext");

                    b.Property<string>("trip_number")
                        .HasColumnType("longtext");

                    b.Property<string>("trip_type")
                        .HasColumnType("longtext");

                    b.Property<int?>("truck_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("tripId");

                    b.HasIndex("co_driver_id");

                    b.HasIndex("driver_id");

                    b.HasIndex("truck_id");

                    b.ToTable("trips");
                });

            modelBuilder.Entity("TMS.src.TripStatus", b =>
                {
                    b.Property<int>("tripStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("tripStatusId"));

                    b.Property<int>("statusName")
                        .HasColumnType("int");

                    b.Property<int>("tripId")
                        .HasColumnType("int");

                    b.Property<int>("truckId")
                        .HasColumnType("int");

                    b.HasKey("tripStatusId");

                    b.HasIndex("tripId")
                        .IsUnique();

                    b.HasIndex("truckId");

                    b.ToTable("tripStatuses");
                });

            modelBuilder.Entity("TMS.src.TruckModel", b =>
                {
                    b.Property<int>("truckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("truckId"));

                    b.Property<string>("cnic_status")
                        .HasColumnType("longtext");

                    b.Property<int?>("co_driver_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("driver_id")
                        .HasColumnType("int");

                    b.Property<string>("engine_capacity")
                        .HasColumnType("longtext");

                    b.Property<string>("fitness_cert_expiry")
                        .HasColumnType("longtext");

                    b.Property<string>("fuel_percentage")
                        .HasColumnType("longtext");

                    b.Property<string>("fuel_type")
                        .HasColumnType("longtext");

                    b.Property<double?>("image_url")
                        .HasColumnType("double");

                    b.Property<string>("insurance_type")
                        .HasColumnType("longtext");

                    b.Property<bool?>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("make")
                        .HasColumnType("longtext");

                    b.Property<int?>("max_load_tons")
                        .HasColumnType("int");

                    b.Property<int?>("mileage_km")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .HasColumnType("longtext");

                    b.Property<string>("permit_type")
                        .HasColumnType("longtext");

                    b.Property<string>("plate_number")
                        .HasColumnType("longtext");

                    b.Property<double?>("rating")
                        .HasColumnType("double");

                    b.Property<string>("registration_expiry")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<string>("sub_status")
                        .HasColumnType("longtext");

                    b.Property<string>("tire_condition")
                        .HasColumnType("longtext");

                    b.Property<int?>("tripId")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("year")
                        .HasColumnType("longtext");

                    b.HasKey("truckId");

                    b.HasIndex("co_driver_id");

                    b.HasIndex("driver_id");

                    b.HasIndex("tripId");

                    b.ToTable("trucks");
                });

            modelBuilder.Entity("TMS.src.UserModel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<string>("age")
                        .HasColumnType("longtext");

                    b.Property<int?>("assigned_truck_id")
                        .HasColumnType("int");

                    b.Property<string>("cnic")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("device_token")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("emergency_contact")
                        .HasColumnType("longtext");

                    b.Property<int?>("experience_years")
                        .HasColumnType("int");

                    b.Property<string>("f_Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_available")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("is_verified")
                        .HasColumnType("longtext");

                    b.Property<string>("l_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("license_number")
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .HasColumnType("longtext");

                    b.Property<string>("phone_no")
                        .HasColumnType("longtext");

                    b.Property<string>("profile_image")
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .HasColumnType("longtext");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("verification_status")
                        .HasColumnType("longtext");

                    b.HasKey("userId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TMS.src.ExpenseModel", b =>
                {
                    b.HasOne("TMS.src.UserModel", "user")
                        .WithMany()
                        .HasForeignKey("added_by");

                    b.HasOne("TMS.src.UserModel", "co_driver")
                        .WithMany()
                        .HasForeignKey("co_driver_id");

                    b.HasOne("TMS.src.UserModel", "driver")
                        .WithMany()
                        .HasForeignKey("driver_id");

                    b.HasOne("TMS.src.ExpenseCategory", "expenseCategory")
                        .WithMany()
                        .HasForeignKey("e_c_id");

                    b.HasOne("TMS.src.TripModel", "trip")
                        .WithMany()
                        .HasForeignKey("trip_id");

                    b.Navigation("co_driver");

                    b.Navigation("driver");

                    b.Navigation("expenseCategory");

                    b.Navigation("trip");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TMS.src.TripModel", b =>
                {
                    b.HasOne("TMS.src.UserModel", "co_driver")
                        .WithMany()
                        .HasForeignKey("co_driver_id");

                    b.HasOne("TMS.src.UserModel", "driver")
                        .WithMany()
                        .HasForeignKey("driver_id");

                    b.HasOne("TMS.src.TruckModel", "truck")
                        .WithMany()
                        .HasForeignKey("truck_id");

                    b.Navigation("co_driver");

                    b.Navigation("driver");

                    b.Navigation("truck");
                });

            modelBuilder.Entity("TMS.src.TripStatus", b =>
                {
                    b.HasOne("TMS.src.TripModel", "trip")
                        .WithOne("tripStatus")
                        .HasForeignKey("TMS.src.TripStatus", "tripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS.src.TruckModel", "truck")
                        .WithMany()
                        .HasForeignKey("truckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("trip");

                    b.Navigation("truck");
                });

            modelBuilder.Entity("TMS.src.TruckModel", b =>
                {
                    b.HasOne("TMS.src.UserModel", "co_driver")
                        .WithMany()
                        .HasForeignKey("co_driver_id");

                    b.HasOne("TMS.src.UserModel", "driver")
                        .WithMany()
                        .HasForeignKey("driver_id");

                    b.HasOne("TMS.src.TripModel", "trip")
                        .WithMany()
                        .HasForeignKey("tripId");

                    b.Navigation("co_driver");

                    b.Navigation("driver");

                    b.Navigation("trip");
                });

            modelBuilder.Entity("TMS.src.TripModel", b =>
                {
                    b.Navigation("tripStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
